let myResume = {
   
    'personal info':{
        'name':'chandru M',
        'D.O.B':'25/09/1999',
        'age':23
    },
        
    'skill':[
        'teamplayer',
        'activelistener',
        'hardworking and determinant'
 ],
     'education':{
        'Qualification':'Bachelore of engineering',
        'department':'mechanical enginerring',
         'college':'Coimbatore institute of technology',
         'Percentage':77,
         'year of passing':2022,

         'secondary degree':{
            'qualification':'Diploma in mechanical engineering',
            'college':'nachimuthu polytechnic college',
            'percentage':91,
            'year of passing':2019

         }
        },
        
    'project':{

        'design':['automatic incence burner using using the CATIA V5','design of security brief case along with finger print access '],
        'development':'design and development of aircraft cockpit lighting control panels',
    },
    'experiance':{
        'role':'design engineer',
        'period of experiance':'10 months'
    },
    'programmingskills':['html', 'css', 'javascript', 'python'],
    
    'co-curriculam':{
        'sports':'cricket',
        'hobbies':'listening to music',
        'entertainment':'treeking'
    }
            
       
     

}